import { Box, Typography } from "@mui/material";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ padding: "50px 0" }}>
        <Typography variant="h1">Go to login page!</Typography>
        <Link href="/api/auth/signin">Login!</Link>
      </Box>
    </>
  );
}
